//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KULUPLER
    {
        public byte KULUID { get; set; }
        public string KULUPAD { get; set; }
    }
}
